### ISSUE TITLE
Typo in Eq.11

### ISSUE THREAD

**Issue by MrSchnappi** [fujiso/SODA#3]
Thank you very much for your work, but I have some doubts while reading the paper: 
(1) Formula 11 mentioned in the paper does not exist (Section 6.1, Detecting Inappropriate captions)；
(2) Regarding Precision and recall, the calculation mentioned in the paper is to calculate pairs, but it is calculated as : max( IoU * Meteor) / size  in the code, which does not match formulas 8 and 9 in the paper.

**Comment by fujiso** [comment]
Thank you for reading the paper!

> (1) Formula 11 mentioned in the paper does not exist (Section 6.1, Detecting Inappropriate captions)；  

I'm sorry, it is a typo of Formula 10.
SODA(c) uses the Formula 10, IoU * Meteor, to both the cost of DP matching and calculating precision/recall/f-score.

> (2) Regarding Precision and recall, the calculation mentioned in the paper is to calculate pairs, but it is calculated as : max( IoU * Meteor) / size in the code, which does not match formulas 8 and 9 in the paper.  

When we calculate soda(c), the input argument of chased_dp_assignment function is an IoU * Meteor score matrix.
In the transition function, scores are recursively added when a predicted proposal matches a gold, as in L163-164.
https://github.com/fujiso/SODA/blob/master/soda.py#L163-L164

Therefore, dp[i, j] is always the sum of the previous matched scores.
It means dp[N-1, M-1] equals to sum of IoU * Meteor score.

**Comment by MrSchnappi** [comment]
OK， I got it ， Thanks a lot ！
